export { default as Bannar } from './BannarBig.jpg'
export { default as Logo } from './LogoFPT.png'
export { default as Banner2 } from './Banner2.png'
export { default as Banner3 } from './Banna3.png'
// Các loại phổ biến
export { default as SanPham1 } from './SanPham1.png'
export { default as SanPham2 } from './SanPham2.jpg'
export { default as SanPham3 } from './SanPham3.jpg'
export { default as SanPham4 } from './SanPham4.jpg'
export { default as SanPham5 } from './SanPham5.jpg'
export { default as SanPham6 } from './SanPham6.jpg'
export { default as SanPham7 } from './SanPham7.jpg'
export { default as SanPham8 } from './SanPham8.jpg'
export { default as SanPham9 } from './SanPham9.jpg'
export { default as SanPham10 } from './SanPham10.jpg'
export { default as SanPham11 } from './SanPham11.jpg'
export { default as SanPham12 } from './SanPham12.jpg'
//
export { default as Product1 } from './Product_Image_1.jpg'
export { default as Product2 } from './Product2.jpg'
export { default as Product3 } from './Product3.jpg'
export { default as Product4 } from './Product4.jpg'
export { default as Product5 } from './Product5.jpg'
export { default as Product6 } from './Product6.jpg'
export { default as Product7 } from './Product7.jpg'
export { default as Product8 } from './Product8.jpg'
export { default as Product9 } from './Product9.jpg'
export { default as Product10 } from './Product10.jpg'

//
export { default as QuangCao1 } from './QuangCao1.jpg'
export { default as QuangCao2 } from './QuangCao2.jpg'
export { default as QuangCao3 } from './QuangCao3.jpg'

//
export { default as QuangCaoTo } from './QuangCaoTo.png'
export { default as TinTuc1 } from './TinTuc1.jpg'
export { default as TinTuc2 } from './TinTuc2.jpg'
export { default as TinTuc3 } from './TinTuc3.jpg'
export { default as Vector } from './Vector.jpg'
export { default as DaiDien1 } from './Avatar.jpg'
export { default as Instagram1 } from './InstagramPost1.jpg'
export { default as Instagram2 } from './InstagramPost2.jpg'
export { default as Instagram3 } from './InstagramPost3.jpg'
export { default as Instagram4 } from './InstagramPost4.jpg'
export { default as Instagram5 } from './InstagramPost5.jpg'
export { default as Instagram6 } from './InstagramPost6.jpg'
export { default as CompannyLogo } from './CompanyLogo.jpg'
export { default as ChuKy } from './Q.png'
export { default as FPTLogo } from './FPT.png'
