export {default as bigContent} from './bigContent.png'
export {default as Content} from './content.png'
export {default as Blueberry} from './blueberry.png'
export {default as Strawberry} from './strawberry.png'
export {default as Maize} from './maize.png'
export {default as Apple} from './apple.png'
export {default as Symbol} from './Symbol.png'
export {default as Content3} from './Content3.jpg'
export {default as img1Content3} from './3content1.png'
export {default as img2Content3} from './3content2.png'
export {default as img3Content3} from './3content3.png'
export {default as Agri} from './agri.png'
export {default as Fresh} from './fresh.png'
export {default as Organic} from './organic.png'
export {default as Content4} from './4content.png'

