export {default as CaiThiaC } from './caithia-c.jpg'
export {default as CaiThia1 } from './caithia-1.jpg'
export {default as CaiThia2 } from './caithia-2.jpg'
export {default as CaiThia3 } from './caithia-3.jpg'
export {default as TaoXanhC } from './taoxanh-c.jpg'
export {default as OtChuongXanhC } from './otchuongxanh-c.jpg'
export {default as BongCaiTrangC } from './bongcaitrang-c.jpg'
export {default as DauBapC } from './daubap.jpg'
export {default as Cart } from './cart.png'
export {default as Heart } from './heart.png'
export {default as Fb } from './fb.png'
export {default as Tw } from './tw.png'
export {default as Pin } from './pin.png'
export {default as Ins } from './ins.png'
export {default as FPT} from './fpt.png'
export {default as Tick} from './tick.png'
export {default as GioHang} from './giohang.png'
export {default as Star1} from './star1.png'
export {default as Star2} from './star2.png'